[package]
name = "life2d"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
line_drawing = "1.0.0"
nannou = "0.18.1"
rand = "0.8.5"
rayon = "1.6.1"
